accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('reservation/',views.myreservation,name='reservation'),
    path('profile/edit',views.edit_profile,name='profile_edit')
    
]

contact/urls.py
from django.urls import include, path
from . import views  

app_name='contact'


urlpatterns = [
    path('',views.send_message, name='contact'),
   
]

doctors/urls.py
from django.urls import path
from .views import DoctorList ,DoctorDetail



app_name = 'doctor'

urlpatterns = [
    path('',DoctorList.as_view(),name='doctors_list'),
    path('<slug:slug>',DoctorDetail.as_view(),name='doctors_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path('doctors/',include('doctors.urls',namespace='doctors')),
    path('',include('settings.urls',namespace='home')),
    path('contact/', include('contact.urls', namespace='contact')),
]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from .views import *


app_name = 'settings'

urlpatterns = [
    path('',home , name='home'),

]

settings/models.py
from django.db import models

# Create your models here.

settings/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'settings/index.html')

settings/templates/settings/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- 
    - primary meta tags
  -->
  <title>KFS HOSPITAL</title>
  <meta name="title" content="helo">
  <meta name="description" content="This is a madical html template made by pro">

  <!-- 
    - favicon
  -->
  <link rel="shortcut icon" href="./favicon.svg" type="image/svg+xml">

  <!-- 
    - google font link
  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500;700&family=Rubik:wght@400;500;700&display=swap"
    rel="stylesheet">

  <!-- 
    - custom css link
  -->
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">


  <!-- 
    - preload images
  -->
  <link rel="preload" as="image" href="{% static '/assets/images/co.jpg' %}">
  <link rel="preload" as="image" href="{% static '/assets/images/co.jpg' %}">

</head>

<body id="top">

  <!-- 
    - #PRELOADER
  -->

  <div class="preloader" data-preloader>
    <div class="circle"></div>
  </div>




  <!-- 
    - #HEADER
  -->

  <header class="header" data-header>
    <div class="container">

      <a href="#" class="logo">
        <img src="{% static '/assets/images/tech.jpg' %}" width="136" height="46" alt="Doclab home">
      </a>

      <nav class="navbar" data-navbar>

        <div class="navbar-top">

          <a href="#" class="logo">
            <img src="% static '/assets/images/tech.jpg'%}" width="136" height="46" alt="kfs">
          </a>

          <button class="nav-close-btn" aria-label="clsoe menu" data-nav-toggler>
            <ion-icon name="close-outline" aria-hidden="true"></ion-icon><!--  here is library to get the icon image-->
          </button>

        </div>

        <ul class="navbar-list">

          <li class="navbar-item">
            <a href="#" class="navbar-link title-md">Home</a>
          </li>

          <li class="navbar-item">
            <a href="{% url 'doctors:doctors_list'%}" class="navbar-link title-md">Doctors</a>
          </li>

          <li class="navbar-item">
            <a href="service.html" class="navbar-link title-md">Services</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="navbar-item">
            <a href="{% url 'accounts:profile'%}" class="navbar-link title-md">Profile</a>
          </li>
          {% else %}
          <li class="navbar-item">
            <a href="{% url 'accounts:signup' %}" class="navbar-link title-md">Signup</a>
          </li>

          <li class="navbar-item">
            <a href="{% url 'login'%}" class="navbar-link title-md">Login</a>

          </li>
          {% endif %}
          <li class="navbar-item">
            <a href="{% url 'contact:contact'%}" class="navbar-link title-md">Contact</a>

          </li>
          <li class="navbar-item">
            <a href="pay.html" class="navbar-link title-md">Payment</a>

          </li>
        </ul>

        <ul class="social-list">

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-twitter"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-facebook"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-pinterest"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-instagram"></ion-icon>
            </a>
          </li>

          <li>
            <a href="" class="social-link">
              <ion-icon name="logo-youtube"></ion-icon>

            </a>
          </li>

        </ul>

      </nav>

      <button class="nav-open-btn" aria-label="open menu" data-nav-toggler>
        <ion-icon name="menu-outline"></ion-icon>
      </button>

      <a href="APPOINTMENT.html" class="btn has-before title-md">Make Appointment</a>



    </div>
  </header>





  <main>
    <article>

      <!-- 
        - #HERO
      -->

      <section class="section hero" style="background-image: url('./assets/images/co-bg.png')" aria-label="home">
        <div class="container">

          <div class="hero-content">

            <p class="hero-subtitle has-before" data-reveal="left">Welcome To KFS</p>

            <h1 class="headline-lg hero-title" data-reveal="left">
              Find Nearest <br>
              Doctor.
            </h1>

            <div class="hero-card" data-reveal="left">

              <p class="title-lg card-text">
                Search doctors. clinics. hospitals. etc.
              </p>

              <div class="wrapper">

                <div class="input-wrapper title-lg">
                  <input type="text" name="location" placeholder="Locations" class="input-field">

                  <ion-icon name="location"></ion-icon>
                </div>

                <button class="btn has-before">
                  <ion-icon name="search"></ion-icon>

                  <span class="span title-md">Find Now</span>
                </button>

              </div>

            </div>

          </div>

          <figure class="hero-banner" data-reveal="right">
            <img src="{% static '/assets/images/co.jpg' %}" width="590" height="517" loading="eager" alt="hero banner"
              class="w-500">
          </figure>


        </div>
      </section>




      <footer class="footer" style="background-image: url('./assets/images/footer-bg.png')">
        <div class="container">

          <div class="section footer-top">

            <div class="footer-brand" data-reveal="bottom">

              <a href="#" class="logo">
                <img src="R.jpg" width="136" height="46" loading="lazy" alt="Doclab home">
              </a>

              <ul class="contact-list has-after">

                <li class="contact-item">

                  <div class="item-icon">
                    <ion-icon name="mail-open-outline"></ion-icon>
                  </div>

                  <div>
                    <p>
                      Main Email : <a href="mailto:contact@website.com"
                        class="contact-link">contact@&shy;website.com</a>
                    </p>

                    <p>
                      Inquiries : <a href="mailto:Info@mail.com" class="contact-link">Info@mail.com</a>
                    </p>
                  </div>

                </li>

                <li class="contact-item">

                  <div class="item-icon">
                    <ion-icon name="call-outline"></ion-icon>
                  </div>

                  <div>
                    <p>
                      Office Telephone : <a href="tel:0029129102320" class="contact-link">0029129102320</a>
                    </p>

                    <p>
                      Mobile : <a href="tel:000232439493" class="contact-link">000 2324 39493</a>
                    </p>
                  </div>

                </li>

              </ul>

            </div>

            <div class="footer-list" data-reveal="bottom">

              <p class="headline-sm footer-list-title">About Us</p>

              <p class="text">
                KFS HOSPITAL
              </p>

              <address class="address">
                <ion-icon name="map-outline"></ion-icon>

                <span class="text">
                  EGYPT kafrelsheikh
                </span>

              </address>
              <address class="address">
                <ion-icon name="map-outline"></ion-icon>

                <span class="text">

                  <div class="qr-container">
                    <h1> QR Code</h1>
                    <img id="img" src="" alt="QR Code" width="150">
                  </div>
                  <script>
                    let img = document.getElementById("img");

                    function myFun() {
                      let value = "https://kfs.edu.eg/hospital/";

                      if (value) {
                        img.src = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${value}`;
                      }
                    }

                    // Call myFun when the page loads
                    window.onload = myFun;
                  </script>
            </div>
            <style>
              .qr-container {
                background-color: white;
                border-radius: 10px;
                box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
                padding: 20px;
                text-align: left;

              }

              #img {
                border: 1px solid #ccc;
                padding: 10px;
                background-color: white;
                border-radius: 10px;
                box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
                margin-right: 250px;

              }

              h1 {
                margin-top: 0;
                color: #333;
              }
            </style>
            </span>

            </address>

          </div>

          <ul class="footer-list" data-reveal="bottom">

            <li>
              <p class="headline-sm footer-list-title">Services</p>
            </li>

            <li>
              <a href="#" class="text footer-link">Conditions</a>
            </li>

            <li>
              <a href="#" class="text footer-link">Listing</a>
            </li>

            <li>
              <a href="#" class="text footer-link">How It Works</a>
            </li>

            <li>
              <a href="#" class="text footer-link">What We Offer</a>
            </li>

            <li>
              <a href="#" class="text footer-link">Latest News</a>
            </li>

            <li>
              <a href="#" class="text footer-link">Contact Us</a>
            </li>

          </ul>

          <ul class="footer-list" data-reveal="bottom">

            <li>
              <p class="headline-sm footer-list-title">Useful Links</p>
            </li>

            <li>
              <a href="#" class="text footer-link">Conditions</a>
            </li>

            <li>
              <a href="#" class="text footer-link">Terms of Use</a>
            </li>

            <li>
              <a href="#" class="text footer-link">Our Services</a>
            </li>

            <li>
              <a href="#" class="text footer-link">Join as a Doctor</a>
            </li>

            <li>
              <a href="#" class="text footer-link">New Guests List</a>
            </li>

            <li>
              <a href="#" class="text footer-link">The Team List</a>
            </li>

          </ul>

          <div class="footer-list" data-reveal="bottom">

            <p class="headline-sm footer-list-title">Subscribe</p>

            <form action="" class="footer-form">
              <input type="email" name="email" placeholder="Email" class="input-field title-lg">

              <button type="submit" class="btn has-before title-md">Subscribe</button>
            </form>

            <p class="text">
              Get the latest updates via email. Any time you may unsubscribe
            </p>

          </div>

        </div>

        <div class="footer-bottom">

          <p class="text copyright">
            2024 KFS HOSPITAL MANAGEMENT
          </p>

          <ul class="social-list">

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-facebook"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-twitter"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-google"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-linkedin"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-pinterest"></ion-icon>
              </a>
            </li>

          </ul>

        </div>

        </div>
      </footer>



      <script src="{% static '/assets/js/script.js' %}"></script>

      <!-- 
    - ionicon link
  -->
      <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
      <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>